FROM debian:buster

USER root

RUN apt-get update
RUN apt-get install -y fai-server
RUN apt-get install -y fai-setup-storage
RUN apt-get install -y qemu-utils
RUN apt-get install -y build-essential

ENV SRC=/home/ngfw/cloud
RUN mkdir -p ${SRC}
VOLUME ${SRC}

WORKDIR ${SRC}

ENTRYPOINT [ "make" ]
