version: '2'
services:
  # build:
  #   image: untangleinc/mfw:build
  #   volumes:
  #     - ./:/home/mfw/openwrt
  #   command: musl
  build-local-container:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ./:/home/ngfw/cloud
    command: azure-image
