FROM debian:stretch-backports

USER root

RUN apt-get update
RUN apt-get install -y fai-server
RUN apt-get install -y build-essential
RUN apt-get install -y fai-doc

ENV SRC=/home/ngfw/cloud
RUN mkdir -p ${SRC}
VOLUME ${SRC}

WORKDIR ${SRC}

ENTRYPOINT [ "make" ]
