#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# currently missing from bootstrap-vz:
# init.d/expand-root
# init.d/generate-ssh-hostkeys (currently done in rc.local/CLOUD)

# work around #869939
fcopy -M /etc/udev/rules.d/98-azure-disable-timesync.rules
