#! /bin/bash -x

set -e

REPOSITORY=$1
DISTRIBUTION=$2

STABLE_DISTRIBUTION=jessie
DISTRIBUTION_DIR=/var/www/public/$REPOSITORY/dists

sudo rm -f $DISTRIBUTION_DIR/$STABLE_DISTRIBUTION
sudo ln -sf $DISTRIBUTION_DIR/$DISTRIBUTION $DISTRIBUTION_DIR/$STABLE_DISTRIBUTION

cd $DISTRIBUTION_DIR/$DISTRIBUTION
sudo rm -f updates
sudo ln -sf ./ ./updates
