Welcome to Debian GNU/Linux ${DEBIAN_VERSION}!

This is a Debian installation ${MEDIA_TYPE},
built on ${BUILD_DATE}.

The default option is 'install'. For maximum
control, you can use the 'expert' option.

If the system fails to boot at all (the typical
symptom is a white screen which doesn't go away),
use 'install video=ofonly' or 'expert video=ofonly'.

The plain options are for the powerpc family of
processors (from 601 to G4). The *64 options are for
64bit powerpc processors, which include the IBM 
Power3, Power4, Power5, ... boxes, as well as the 
Apple G5 boxes. Press the tab key for a list of
options, or type 'help' for help.

************************************
If in doubt, just choose 'install', and if that 
doesn't work, try 'install video=ofonly'.
************************************
