#! /bin/bash

# template expansion for sources.list:
# replace {untangle_mirror} with the value of $untangle_mirror
# replace {untangle_release} with the value of $untangle_release

# $1 is the class name used
# $2 is the path to the file copied

# check if a variable of the form {varname} was used at all
grep -q '{' $2 || exit 0

if [ -z "$untangle_mirror" ]; then
    echo "\$untangle_mirror is undefined. Not substituting in $2."
else
    sed -i -e "s#{untangle_mirror}#$untangle_mirror#g" $2
fi

if [ -z "$untangle_release" ]; then
    echo "\$untangle_release not defined. not substituting in $2."
else
    sed -i -e "s#{untangle_release}#$untangle_release#g" $2
fi
