#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# currently missing from bootstrap-vz:
# init.d/expand-root

# Workaround for https://github.com/GoogleCloudPlatform/compute-image-packages/issues/504
# Remove the following for loop once Google has released a fix for this issue into the
# version of their guest agent that we're using.
for cipher in ed25519 ecdsa rsa; do
  touch "$target/etc/ssh/ssh_host_${cipher}_key"
done
