#! /bin/bash

fcopy -BM /etc/hostname

sed -i "s/PermitRootLogin yes/PermitRootLogin without-password/" $target/etc/ssh/sshd_config
ainsl /etc/ssh/sshd_config 'ClientAliveInterval 120'

ainsl -a /etc/modprobe.d/blacklist.conf 'blacklist pcspkr'
ainsl -a /etc/modprobe.d/blacklist.conf 'blacklist floppy'

rm -f $target/etc/resolv.conf \
      $target/etc/mailname \
      $target/etc/machine-id \
      $target/var/lib/dbus/machine-id

touch $target/etc/machine-id

shred --remove $target/etc/ssh/ssh_host_*
