#!/bin/bash

# template expansion for this to work we need gettext-base package as dependency
#
# $1 is the class name used
# $2 is the path to the file copied over

envsubst < $2 > $2.tmp
mv $2.tmp $2
