#! /bin/bash

ainsl -a /etc/modprobe.d/blacklist.conf 'blacklist pcspkr'
ainsl -a /etc/modprobe.d/blacklist.conf 'blacklist floppy'

rm -f $target/etc/resolv.conf \
      $target/etc/mailname \
      $target/etc/machine-id \
      $target/var/lib/dbus/machine-id

rm -rf $target/var/cache/apt/*
rm -rf $target/var/lib/apt/lists/*
rm -f $target/var/lib/dpkg/available*

touch $target/etc/machine-id
touch $target/var/lib/dpkg/available

shred --remove $target/etc/ssh/ssh_host_*
